# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Deploy]')"
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots test
      
  build:
    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, '[Deploy]')"

    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    -
      name: Test with Maven
      run: mvn --batch-mode --update-snapshots test
    - 
      name: Package with Maven
      run: mvn --batch-mode --update-snapshots package
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push zone
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: danieljodlos/gmm-indexer-fork:latest
        
    -
      name: Build and push test image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: Dockerfile.tests
        tags: danieljodlos/gmm-tester:latest
